### ISSUE TITLE
Unable to clone project

### ISSUE THREAD

**Issue by tsctrl** [embeddedartistry/arduino-logger#25]
hi i try to clone project to my local but getting error in multiple files one example as below:

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:embeddedartistry/cppcheck-rules.git' into submodule path 'C:/arduino-logger/build/analysis/cppcheck/cppcheck-rules' failed
Failed to clone 'analysis/cppcheck/cppcheck-rules'. Retry scheduled
Cloning into 'C:/arduino-logger/build/analysis/vale/vale-styleguide'...
fatal: Could not read from remote repository.

thank you

**Comment by tsctrl** [comment]
![image](https://user-images.githubusercontent.com/75555993/136693780-e404f1a3-d265-4ea6-b9ea-75c28f924e2c.png)

**Comment by phillipjohnston** [comment]
Ah, this means you don't have SSH keys set up for GitHub, which the git@ checkout requires. I will get the submodule switched to https:// though.

**Comment by phillipjohnston** [comment]
Should work for you now, please confirm!
